import logging


def raise_exception(exception: Exception):
    logging.warning(exception)
